# Generated by Django 5.2.7 on 2025-10-16 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salud_vital', '0002_paciente_genero_alter_consultamedica_paciente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='genero',
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='diagnostico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas_realizadas', to='salud_vital.medico'),
        ),
        migrations.AlterField(
            model_name='recetamedica',
            name='frecuencia',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='recetamedica',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recetas', to='salud_vital.medicamento'),
        ),
        migrations.AlterField(
            model_name='recetamedica',
            name='tratamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='salud_vital.tratamiento'),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to='salud_vital.consultamedica'),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='fecha_fin',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='CitaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_cita', models.DateTimeField()),
                ('estado', models.CharField(choices=[('Programada', 'Programada'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada'), ('Realizada', 'Realizada')], default='Programada', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='salud_vital.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='salud_vital.paciente')),
            ],
            options={
                'verbose_name': 'Cita Médica',
                'verbose_name_plural': 'Citas Médicas',
                'db_table': 'citas_medicas',
                'ordering': ['-fecha_hora_cita'],
            },
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consulta_generada', to='salud_vital.citamedica'),
        ),
        migrations.CreateModel(
            name='HistorialClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_sanguineo', models.CharField(blank=True, max_length=5, null=True)),
                ('alergias_conocidas', models.TextField(blank=True, null=True)),
                ('enfermedades_cronicas', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historial_clinico', to='salud_vital.paciente')),
            ],
            options={
                'verbose_name': 'Historial Clínico',
                'verbose_name_plural': 'Historiales Clínicos',
                'db_table': 'historiales_clinicos',
            },
        ),
    ]
