# Generated by Django 5.2.7 on 2025-10-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salud_vital', '0003_remove_paciente_genero_consultamedica_diagnostico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citamedica',
            name='motivo',
            field=models.TextField(blank=True, help_text='Motivo de la cita médica', null=True),
        ),
        migrations.AddField(
            model_name='citamedica',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones adicionales', null=True),
        ),
    ]
